[2025-02-25T12:27:01.401885+00:00] console.CRITICAL: Error thrown while running command "list --format=xml". Message: "Class "App\ScheduleJobs\PasswordMigrationJob" not found" {"exception":"[object] (Error(code: 0): Class \"App\\ScheduleJobs\\PasswordMigrationJob\" not found at E:\\Export\\Task Management system Symfony\\task_management\\src\\Command\\MigratePasswordsCommand.php:35)","command":"list --format=xml","message":"Class \"App\\ScheduleJobs\\PasswordMigrationJob\" not found"} []
[2025-02-25T12:27:01.411569+00:00] php.CRITICAL: Uncaught Error: Class "App\ScheduleJobs\PasswordMigrationJob" not found {"exception":"[object] (Error(code: 0): Class \"App\\ScheduleJobs\\PasswordMigrationJob\" not found at E:\\Export\\Task Management system Symfony\\task_management\\src\\Command\\MigratePasswordsCommand.php:35)"} []
[2025-02-25T12:27:01.855526+00:00] console.CRITICAL: Error thrown while running command "list --format=xml". Message: "Class "App\ScheduleJobs\PasswordMigrationJob" not found" {"exception":"[object] (Error(code: 0): Class \"App\\ScheduleJobs\\PasswordMigrationJob\" not found at E:\\Export\\Task Management system Symfony\\task_management\\src\\Command\\MigratePasswordsCommand.php:35)","command":"list --format=xml","message":"Class \"App\\ScheduleJobs\\PasswordMigrationJob\" not found"} []
[2025-02-25T12:27:01.857552+00:00] php.CRITICAL: Uncaught Error: Class "App\ScheduleJobs\PasswordMigrationJob" not found {"exception":"[object] (Error(code: 0): Class \"App\\ScheduleJobs\\PasswordMigrationJob\" not found at E:\\Export\\Task Management system Symfony\\task_management\\src\\Command\\MigratePasswordsCommand.php:35)"} []
[2025-02-25T12:37:50.905031+00:00] request.CRITICAL: Uncaught PHP Exception TypeError: "App\Config\Security\UserAuthenticator::onAuthenticationFailure(): Argument #2 ($exception) must be of type Symfony\Component\Security\Core\Exception\AuthenticationException, Exception given, called in E:\Export\Task Management system Symfony\task_management\src\Controller\SecurityController.php on line 50" at UserAuthenticator.php line 93 {"exception":"[object] (TypeError(code: 0): App\\Config\\Security\\UserAuthenticator::onAuthenticationFailure(): Argument #2 ($exception) must be of type Symfony\\Component\\Security\\Core\\Exception\\AuthenticationException, Exception given, called in E:\\Export\\Task Management system Symfony\\task_management\\src\\Controller\\SecurityController.php on line 50 at E:\\Export\\Task Management system Symfony\\task_management\\src\\Config\\Security\\UserAuthenticator.php:93)"} []
[2025-02-25T12:38:01.650355+00:00] request.CRITICAL: Uncaught PHP Exception TypeError: "App\Config\Security\UserAuthenticator::onAuthenticationFailure(): Argument #2 ($exception) must be of type Symfony\Component\Security\Core\Exception\AuthenticationException, Exception given, called in E:\Export\Task Management system Symfony\task_management\src\Controller\SecurityController.php on line 50" at UserAuthenticator.php line 93 {"exception":"[object] (TypeError(code: 0): App\\Config\\Security\\UserAuthenticator::onAuthenticationFailure(): Argument #2 ($exception) must be of type Symfony\\Component\\Security\\Core\\Exception\\AuthenticationException, Exception given, called in E:\\Export\\Task Management system Symfony\\task_management\\src\\Controller\\SecurityController.php on line 50 at E:\\Export\\Task Management system Symfony\\task_management\\src\\Config\\Security\\UserAuthenticator.php:93)"} []
[2025-02-25T12:59:44.617842+00:00] request.CRITICAL: Uncaught PHP Exception TypeError: "App\Config\Security\UserAuthenticator::onAuthenticationFailure(): Argument #2 ($exception) must be of type Symfony\Component\Security\Core\Exception\AuthenticationException, Doctrine\DBAL\Exception\ConnectionException given, called in E:\Export\Task Management system Symfony\task_management\src\Controller\SecurityController.php on line 50" at UserAuthenticator.php line 93 {"exception":"[object] (TypeError(code: 0): App\\Config\\Security\\UserAuthenticator::onAuthenticationFailure(): Argument #2 ($exception) must be of type Symfony\\Component\\Security\\Core\\Exception\\AuthenticationException, Doctrine\\DBAL\\Exception\\ConnectionException given, called in E:\\Export\\Task Management system Symfony\\task_management\\src\\Controller\\SecurityController.php on line 50 at E:\\Export\\Task Management system Symfony\\task_management\\src\\Config\\Security\\UserAuthenticator.php:93)"} []
[2025-02-25T16:31:33.083692+00:00] request.CRITICAL: Uncaught PHP Exception TypeError: "App\Config\Security\UserAuthenticator::onAuthenticationFailure(): Argument #2 ($exception) must be of type Symfony\Component\Security\Core\Exception\AuthenticationException, Doctrine\DBAL\Exception\ConnectionException given, called in E:\Export\Task Management system Symfony\task_management\src\Controller\SecurityController.php on line 50" at UserAuthenticator.php line 93 {"exception":"[object] (TypeError(code: 0): App\\Config\\Security\\UserAuthenticator::onAuthenticationFailure(): Argument #2 ($exception) must be of type Symfony\\Component\\Security\\Core\\Exception\\AuthenticationException, Doctrine\\DBAL\\Exception\\ConnectionException given, called in E:\\Export\\Task Management system Symfony\\task_management\\src\\Controller\\SecurityController.php on line 50 at E:\\Export\\Task Management system Symfony\\task_management\\src\\Config\\Security\\UserAuthenticator.php:93)"} []
